# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a261b06bc29f5519525454feb75a8ee4dd292867e2d66d089a1cdf1ade7d558429011e6b020f68306d5aa82da2cc156d9d5b429c78120d2376b3da429d66425d

test:
  secret_key_base: 11d3a4cb818e19d1aa9c0c1ae368ba1b4062cf7324b4cdac85910a6ff247529f0869c557311a10f91606f2f9a3ebcd0ae8806607ca380b99b292eeb9817dd936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
